### ISSUE TITLE
Issue setting up this app

### ISSUE THREAD

**Issue by agroebe** [Shopify/shopify-marketplaces-admin-app#8]
Is this sample app even maintained and working?

I was referred to this repository from the Shopify marketplaces documentation and this has been an absolute nightmare to setup. I fixed most of the setup issues and have the app server running locally, but there's all kind of console errors as shown below:

![chrome_2022-05-03_00-06-20](https://user-images.githubusercontent.com/40124525/166406766-4c6587d2-3a14-4219-85d6-f6359af1094a.png)

Any ideas?

**Comment by SerhiDi** [comment]
@agroebe hello,
I found this issue almost 2 months ago.
[Issue link](https://github.com/Shopify/shopify-marketplaces-admin-app/issues/3).
There are no solutions and corrections in the project and most likely will not be. Dead project.

**Comment by misshula** [comment]
appreciate the feedback! we will take a look early next week and report back. sorry for the confusion.

**Comment by misshula** [comment]
I've put up [a PR](https://github.com/Shopify/shopify-marketplaces-admin-app/pull/11) to try to resolve these issues. I will get someone to review tomorrow. Not sure if this is the same issue or not, but hoping this fixes what you are both seeing.

**Comment by komal1118** [comment]
We have checked those.  We might be missing something.  We created the cards using the codes available on https://polaris.shopify.com/components/get-started - there is however, no code that can help something connect it all together.

**Comment by misshula** [comment]
@ChiefGearHead what starting url are you trying to access? I have [a PR](https://github.com/Shopify/shopify-marketplaces-admin-app/pull/12) to accommodate for different version of shopify-cli 

ie: replace `auth` with `login` of vice versa depending on version of cli.

**Comment by misshula** [comment]
it should I will merge and you can re-pull

**Comment by misshula** [comment]
should be closed with https://github.com/Shopify/shopify-marketplaces-admin-app/pull/12

**Comment by ChiefGearHead** [comment]
Thank you @misshula!

**Comment by ChiefGearHead** [comment]
We pulled the update and redeployed, and now it seems that as soon as we launch the app, we get a quick flash of content and then a blank screen. Do you have any ideas on how we can fix this? This is still the out-of-the-box code with the example straight from the Channel UI docs homepage: https://github.com/Shopify/channels-ui-docs. If it helps and you have the time, we can jump on a zoom as well to demonstrate. The code in question is below:

```
import React from 'react';
import {ExtendedAppProvider, IntroductionPage} from '@shopify/channels-ui';
import {Outlet} from 'react-router';
import polarisTranslations from '@shopify/polaris/locales/en.json';
import translations from '@shopify/channels-ui/locales/en.json';
import GraphQLProvider from './GraphQL';
import Link from './Link';

import '@shopify/polaris/dist/styles.css';
import '@shopify/channels-ui/dist/styles.css';
import RoutePropagator from './RoutePropagator';
import {Card, Button} from '@shopify/polaris';

const AppProvider = () => {
  return (
    <ExtendedAppProvider
      polaris={{i18n: polarisTranslations, linkComponent: Link}}
      i18n={translations}
      config={{
        host: new URL(location).searchParams.get('host'),
        apiKey: API_KEY,
        forceRedirect: true,
      }}
    >
      <IntroductionPage title="Example channel">
        <Card title="Welcome" sectioned>
          <Button onClick={() => alert('Button clicked!')}>
            Example button
          </Button>
        </Card>
      </IntroductionPage>
      <GraphQLProvider>
        <Outlet />
        <RoutePropagator />
      </GraphQLProvider>
    </ExtendedAppProvider>
  );
};

export default AppProvider;
```

**Comment by misshula** [comment]
>Do you have any ideas on how we can fix this? 

Can you try updating to the latest [Shopify CLI](https://shopify.dev/apps/tools/cli)?  Can you also share your console logs?

**Comment by JohnFoxtrot** [comment]
@misshula Cloned after the PR you linked was committed (cloned late July 2022) and still having the same issue as @agroebe. Using CLI 2.20.1.

Confusing since it worked during the PR review... 

Any other suggestions?

**Comment by misshula** [comment]
thanks for the detail @JohnFoxtrot  - we will take a look to see what's happening. on quick look, you've taken the right approach to debug - not certain why the `adminShop` is `undefined`

**Comment by JohnFoxtrot** [comment]
Looking at the CLI log for `Shopify App Serve`, after I install the unlisted app I get the following error:

```
TypeError: Cannot read properties of null (reading 'storefrontAccessToken')
at _callee$ (C:\shopify-marketplaces-admin-app\server\handlers\mutations\/create-storefront-access-token.js:22:53)
at tryCatch (C:\shopify-marketplaces-admin-app\node_modules\regenerator-runtime\runtime.js:63:40)
at Generator.invoke [as _invoke] (C:\shopify-marketplaces-admin-app\node_modules\regenerator-runtime\runtime.js:294:22)
at Generator.next (C:\shopify-marketplaces-admin-app\node_modules\regenerator-runtime\runtime.js:119:21)
at asyncGeneratorStep (C:\shopify-marketplaces-admin-app\server\handlers\mutations\create-storefront-access-token.js:10:103)
at _next (C:\shopify-marketplaces-admin-app\server\handlers\mutations\create-storefront-access-token.js:12:194)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

The line reference in create-storefront-access-token: is the mutation for the access token which is returning null:
```
  return resp.body.data.storefrontAccessTokenCreate.storefrontAccessToken
    .accessToken;
```

With respect to that line, my IDE is throwing an error that "storefrontAccessTokenCreate" is an unresolved variable. Is this line accurate?

Presumably this issue is cascading and causing the other gql/rest calls to return null as well?

**Comment by misshula** [comment]
@JohnFoxtrot have you setup your app as a Sales Channel?

**Comment by JohnFoxtrot** [comment]
@misshula It is now.... 😑 

Thanks - appreciate it

**Comment by misshula** [comment]
awesome!
